FROM node:20-alpine AS builder

# RUN addgroup --gid 1000 user \
#     && adduser --uid 1000 -gid 1001 --disabled-password --gecos "" user
WORKDIR /home/user

COPY . .

# RUN npm install --omit=dev
RUN npm install
RUN npm run build


FROM nginx:1.27-alpine AS runner

# RUN addgroup --gid 1000 user \
#     && adduser --uid 1000 --gid 1000 --disabled-password --gecos "" user
WORKDIR /home/user

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/user/dist /usr/share/nginx/html

# USER 1000

EXPOSE 80
